name: wsbermuda
description: Demo debug web server built using the shelf package
version: 0.0.1
#homepage: https://github.com/FredLuddy/wsbermuda
#author: fredericluddy <fred.luddy@gmail.com>

environment:
  sdk: '>=1.24.1 <2.0.0'

dependencies:
  args: ^0.13.7
  shelf: ^0.6.0
  shelf_route: any
  shelf_proxy: any
  browser: ^0.10.0

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:

- test/pub_serve:
    $include: test/**_test.dart
    
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
